/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PairRouteImport } from './routes/pair'
import { Route as HarveyRouteImport } from './routes/harvey'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as PairedRouteImport } from './routes/_paired'
import { Route as PairedIndexRouteImport } from './routes/_paired/index'
import { Route as PairedKmartRouteImport } from './routes/_paired/kmart'
import { Route as PairedJbhifiRouteImport } from './routes/_paired/jbhifi'
import { Route as ApiPublicShopifyRouteImport } from './routes/api/public/shopify'
import { Route as ApiPublicExecTestRouteImport } from './routes/api/public/exec-test'
import { Route as ApiPublicExecMilestonesRouteImport } from './routes/api/public/exec-milestones'
import { Route as ApiPublicRunnerReportRouteImport } from './routes/api/public/runner.report'
import { Route as ApiPublicRunnerPollRouteImport } from './routes/api/public/runner.poll'
import { Route as ApiPublicRunnerPairRouteImport } from './routes/api/public/runner.pair'
import { Route as ApiPublicDesktopValidateKeyRouteImport } from './routes/api/public/desktop.validate-key'
import { Route as ApiPublicDesktopSetupRouteImport } from './routes/api/public/desktop.setup'
import { Route as ApiPublicDesktopPortableRouteImport } from './routes/api/public/desktop.portable'
import { Route as ApiPublicDesktopHyperProvisionRouteImport } from './routes/api/public/desktop.hyper-provision'

const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const HarveyRoute = HarveyRouteImport.update({
  id: '/harvey',
  path: '/harvey',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const PairedRoute = PairedRouteImport.update({
  id: '/_paired',
  getParentRoute: () => rootRouteImport,
} as any)
const PairedIndexRoute = PairedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PairedRoute,
} as any)
const PairedKmartRoute = PairedKmartRouteImport.update({
  id: '/kmart',
  path: '/kmart',
  getParentRoute: () => PairedRoute,
} as any)
const PairedJbhifiRoute = PairedJbhifiRouteImport.update({
  id: '/jbhifi',
  path: '/jbhifi',
  getParentRoute: () => PairedRoute,
} as any)
const ApiPublicShopifyRoute = ApiPublicShopifyRouteImport.update({
  id: '/api/public/shopify',
  path: '/api/public/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExecTestRoute = ApiPublicExecTestRouteImport.update({
  id: '/api/public/exec-test',
  path: '/api/public/exec-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExecMilestonesRoute = ApiPublicExecMilestonesRouteImport.update({
  id: '/api/public/exec-milestones',
  path: '/api/public/exec-milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunnerReportRoute = ApiPublicRunnerReportRouteImport.update({
  id: '/api/public/runner/report',
  path: '/api/public/runner/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunnerPollRoute = ApiPublicRunnerPollRouteImport.update({
  id: '/api/public/runner/poll',
  path: '/api/public/runner/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunnerPairRoute = ApiPublicRunnerPairRouteImport.update({
  id: '/api/public/runner/pair',
  path: '/api/public/runner/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDesktopValidateKeyRoute =
  ApiPublicDesktopValidateKeyRouteImport.update({
    id: '/api/public/desktop/validate-key',
    path: '/api/public/desktop/validate-key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDesktopSetupRoute = ApiPublicDesktopSetupRouteImport.update({
  id: '/api/public/desktop/setup',
  path: '/api/public/desktop/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDesktopPortableRoute =
  ApiPublicDesktopPortableRouteImport.update({
    id: '/api/public/desktop/portable',
    path: '/api/public/desktop/portable',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDesktopHyperProvisionRoute =
  ApiPublicDesktopHyperProvisionRouteImport.update({
    id: '/api/public/desktop/hyper-provision',
    path: '/api/public/desktop/hyper-provision',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PairedIndexRoute
  '/download': typeof DownloadRoute
  '/harvey': typeof HarveyRoute
  '/pair': typeof PairRoute
  '/jbhifi': typeof PairedJbhifiRoute
  '/kmart': typeof PairedKmartRoute
  '/api/public/exec-milestones': typeof ApiPublicExecMilestonesRoute
  '/api/public/exec-test': typeof ApiPublicExecTestRoute
  '/api/public/shopify': typeof ApiPublicShopifyRoute
  '/api/public/desktop/hyper-provision': typeof ApiPublicDesktopHyperProvisionRoute
  '/api/public/desktop/portable': typeof ApiPublicDesktopPortableRoute
  '/api/public/desktop/setup': typeof ApiPublicDesktopSetupRoute
  '/api/public/desktop/validate-key': typeof ApiPublicDesktopValidateKeyRoute
  '/api/public/runner/pair': typeof ApiPublicRunnerPairRoute
  '/api/public/runner/poll': typeof ApiPublicRunnerPollRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRoutesByTo {
  '/download': typeof DownloadRoute
  '/harvey': typeof HarveyRoute
  '/pair': typeof PairRoute
  '/jbhifi': typeof PairedJbhifiRoute
  '/kmart': typeof PairedKmartRoute
  '/': typeof PairedIndexRoute
  '/api/public/exec-milestones': typeof ApiPublicExecMilestonesRoute
  '/api/public/exec-test': typeof ApiPublicExecTestRoute
  '/api/public/shopify': typeof ApiPublicShopifyRoute
  '/api/public/desktop/hyper-provision': typeof ApiPublicDesktopHyperProvisionRoute
  '/api/public/desktop/portable': typeof ApiPublicDesktopPortableRoute
  '/api/public/desktop/setup': typeof ApiPublicDesktopSetupRoute
  '/api/public/desktop/validate-key': typeof ApiPublicDesktopValidateKeyRoute
  '/api/public/runner/pair': typeof ApiPublicRunnerPairRoute
  '/api/public/runner/poll': typeof ApiPublicRunnerPollRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_paired': typeof PairedRouteWithChildren
  '/download': typeof DownloadRoute
  '/harvey': typeof HarveyRoute
  '/pair': typeof PairRoute
  '/_paired/jbhifi': typeof PairedJbhifiRoute
  '/_paired/kmart': typeof PairedKmartRoute
  '/_paired/': typeof PairedIndexRoute
  '/api/public/exec-milestones': typeof ApiPublicExecMilestonesRoute
  '/api/public/exec-test': typeof ApiPublicExecTestRoute
  '/api/public/shopify': typeof ApiPublicShopifyRoute
  '/api/public/desktop/hyper-provision': typeof ApiPublicDesktopHyperProvisionRoute
  '/api/public/desktop/portable': typeof ApiPublicDesktopPortableRoute
  '/api/public/desktop/setup': typeof ApiPublicDesktopSetupRoute
  '/api/public/desktop/validate-key': typeof ApiPublicDesktopValidateKeyRoute
  '/api/public/runner/pair': typeof ApiPublicRunnerPairRoute
  '/api/public/runner/poll': typeof ApiPublicRunnerPollRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/harvey'
    | '/pair'
    | '/jbhifi'
    | '/kmart'
    | '/api/public/exec-milestones'
    | '/api/public/exec-test'
    | '/api/public/shopify'
    | '/api/public/desktop/hyper-provision'
    | '/api/public/desktop/portable'
    | '/api/public/desktop/setup'
    | '/api/public/desktop/validate-key'
    | '/api/public/runner/pair'
    | '/api/public/runner/poll'
    | '/api/public/runner/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/download'
    | '/harvey'
    | '/pair'
    | '/jbhifi'
    | '/kmart'
    | '/'
    | '/api/public/exec-milestones'
    | '/api/public/exec-test'
    | '/api/public/shopify'
    | '/api/public/desktop/hyper-provision'
    | '/api/public/desktop/portable'
    | '/api/public/desktop/setup'
    | '/api/public/desktop/validate-key'
    | '/api/public/runner/pair'
    | '/api/public/runner/poll'
    | '/api/public/runner/report'
  id:
    | '__root__'
    | '/_paired'
    | '/download'
    | '/harvey'
    | '/pair'
    | '/_paired/jbhifi'
    | '/_paired/kmart'
    | '/_paired/'
    | '/api/public/exec-milestones'
    | '/api/public/exec-test'
    | '/api/public/shopify'
    | '/api/public/desktop/hyper-provision'
    | '/api/public/desktop/portable'
    | '/api/public/desktop/setup'
    | '/api/public/desktop/validate-key'
    | '/api/public/runner/pair'
    | '/api/public/runner/poll'
    | '/api/public/runner/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PairedRoute: typeof PairedRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  HarveyRoute: typeof HarveyRoute
  PairRoute: typeof PairRoute
  ApiPublicExecMilestonesRoute: typeof ApiPublicExecMilestonesRoute
  ApiPublicExecTestRoute: typeof ApiPublicExecTestRoute
  ApiPublicShopifyRoute: typeof ApiPublicShopifyRoute
  ApiPublicDesktopHyperProvisionRoute: typeof ApiPublicDesktopHyperProvisionRoute
  ApiPublicDesktopPortableRoute: typeof ApiPublicDesktopPortableRoute
  ApiPublicDesktopSetupRoute: typeof ApiPublicDesktopSetupRoute
  ApiPublicDesktopValidateKeyRoute: typeof ApiPublicDesktopValidateKeyRoute
  ApiPublicRunnerPairRoute: typeof ApiPublicRunnerPairRoute
  ApiPublicRunnerPollRoute: typeof ApiPublicRunnerPollRoute
  ApiPublicRunnerReportRoute: typeof ApiPublicRunnerReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvey': {
      id: '/harvey'
      path: '/harvey'
      fullPath: '/harvey'
      preLoaderRoute: typeof HarveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_paired': {
      id: '/_paired'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PairedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_paired/': {
      id: '/_paired/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PairedIndexRouteImport
      parentRoute: typeof PairedRoute
    }
    '/_paired/kmart': {
      id: '/_paired/kmart'
      path: '/kmart'
      fullPath: '/kmart'
      preLoaderRoute: typeof PairedKmartRouteImport
      parentRoute: typeof PairedRoute
    }
    '/_paired/jbhifi': {
      id: '/_paired/jbhifi'
      path: '/jbhifi'
      fullPath: '/jbhifi'
      preLoaderRoute: typeof PairedJbhifiRouteImport
      parentRoute: typeof PairedRoute
    }
    '/api/public/shopify': {
      id: '/api/public/shopify'
      path: '/api/public/shopify'
      fullPath: '/api/public/shopify'
      preLoaderRoute: typeof ApiPublicShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exec-test': {
      id: '/api/public/exec-test'
      path: '/api/public/exec-test'
      fullPath: '/api/public/exec-test'
      preLoaderRoute: typeof ApiPublicExecTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exec-milestones': {
      id: '/api/public/exec-milestones'
      path: '/api/public/exec-milestones'
      fullPath: '/api/public/exec-milestones'
      preLoaderRoute: typeof ApiPublicExecMilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/report': {
      id: '/api/public/runner/report'
      path: '/api/public/runner/report'
      fullPath: '/api/public/runner/report'
      preLoaderRoute: typeof ApiPublicRunnerReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/poll': {
      id: '/api/public/runner/poll'
      path: '/api/public/runner/poll'
      fullPath: '/api/public/runner/poll'
      preLoaderRoute: typeof ApiPublicRunnerPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/pair': {
      id: '/api/public/runner/pair'
      path: '/api/public/runner/pair'
      fullPath: '/api/public/runner/pair'
      preLoaderRoute: typeof ApiPublicRunnerPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop/validate-key': {
      id: '/api/public/desktop/validate-key'
      path: '/api/public/desktop/validate-key'
      fullPath: '/api/public/desktop/validate-key'
      preLoaderRoute: typeof ApiPublicDesktopValidateKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop/setup': {
      id: '/api/public/desktop/setup'
      path: '/api/public/desktop/setup'
      fullPath: '/api/public/desktop/setup'
      preLoaderRoute: typeof ApiPublicDesktopSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop/portable': {
      id: '/api/public/desktop/portable'
      path: '/api/public/desktop/portable'
      fullPath: '/api/public/desktop/portable'
      preLoaderRoute: typeof ApiPublicDesktopPortableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop/hyper-provision': {
      id: '/api/public/desktop/hyper-provision'
      path: '/api/public/desktop/hyper-provision'
      fullPath: '/api/public/desktop/hyper-provision'
      preLoaderRoute: typeof ApiPublicDesktopHyperProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PairedRouteChildren {
  PairedJbhifiRoute: typeof PairedJbhifiRoute
  PairedKmartRoute: typeof PairedKmartRoute
  PairedIndexRoute: typeof PairedIndexRoute
}

const PairedRouteChildren: PairedRouteChildren = {
  PairedJbhifiRoute: PairedJbhifiRoute,
  PairedKmartRoute: PairedKmartRoute,
  PairedIndexRoute: PairedIndexRoute,
}

const PairedRouteWithChildren =
  PairedRoute._addFileChildren(PairedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PairedRoute: PairedRouteWithChildren,
  DownloadRoute: DownloadRoute,
  HarveyRoute: HarveyRoute,
  PairRoute: PairRoute,
  ApiPublicExecMilestonesRoute: ApiPublicExecMilestonesRoute,
  ApiPublicExecTestRoute: ApiPublicExecTestRoute,
  ApiPublicShopifyRoute: ApiPublicShopifyRoute,
  ApiPublicDesktopHyperProvisionRoute: ApiPublicDesktopHyperProvisionRoute,
  ApiPublicDesktopPortableRoute: ApiPublicDesktopPortableRoute,
  ApiPublicDesktopSetupRoute: ApiPublicDesktopSetupRoute,
  ApiPublicDesktopValidateKeyRoute: ApiPublicDesktopValidateKeyRoute,
  ApiPublicRunnerPairRoute: ApiPublicRunnerPairRoute,
  ApiPublicRunnerPollRoute: ApiPublicRunnerPollRoute,
  ApiPublicRunnerReportRoute: ApiPublicRunnerReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
