/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PairRouteImport } from './routes/pair'
import { Route as PairedRouteImport } from './routes/_paired'
import { Route as PairedIndexRouteImport } from './routes/_paired/index'
import { Route as PairedKmartRouteImport } from './routes/_paired/kmart'
import { Route as PairedJbhifiRouteImport } from './routes/_paired/jbhifi'
import { Route as ApiPublicShopifyRouteImport } from './routes/api/public/shopify'
import { Route as ApiPublicExecTestRouteImport } from './routes/api/public/exec-test'
import { Route as ApiPublicRunnerReportRouteImport } from './routes/api/public/runner.report'
import { Route as ApiPublicRunnerPollRouteImport } from './routes/api/public/runner.poll'
import { Route as ApiPublicRunnerPairRouteImport } from './routes/api/public/runner.pair'

const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const PairedRoute = PairedRouteImport.update({
  id: '/_paired',
  getParentRoute: () => rootRouteImport,
} as any)
const PairedIndexRoute = PairedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PairedRoute,
} as any)
const PairedKmartRoute = PairedKmartRouteImport.update({
  id: '/kmart',
  path: '/kmart',
  getParentRoute: () => PairedRoute,
} as any)
const PairedJbhifiRoute = PairedJbhifiRouteImport.update({
  id: '/jbhifi',
  path: '/jbhifi',
  getParentRoute: () => PairedRoute,
} as any)
const ApiPublicShopifyRoute = ApiPublicShopifyRouteImport.update({
  id: '/api/public/shopify',
  path: '/api/public/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExecTestRoute = ApiPublicExecTestRouteImport.update({
  id: '/api/public/exec-test',
  path: '/api/public/exec-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunnerReportRoute = ApiPublicRunnerReportRouteImport.update({
  id: '/api/public/runner/report',
  path: '/api/public/runner/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunnerPollRoute = ApiPublicRunnerPollRouteImport.update({
  id: '/api/public/runner/poll',
  path: '/api/public/runner/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunnerPairRoute = ApiPublicRunnerPairRouteImport.update({
  id: '/api/public/runner/pair',
  path: '/api/public/runner/pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PairedIndexRoute
  '/pair': typeof PairRoute
  '/jbhifi': typeof PairedJbhifiRoute
  '/kmart': typeof PairedKmartRoute
  '/api/public/exec-test': typeof ApiPublicExecTestRoute
  '/api/public/shopify': typeof ApiPublicShopifyRoute
  '/api/public/runner/pair': typeof ApiPublicRunnerPairRoute
  '/api/public/runner/poll': typeof ApiPublicRunnerPollRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/jbhifi': typeof PairedJbhifiRoute
  '/kmart': typeof PairedKmartRoute
  '/': typeof PairedIndexRoute
  '/api/public/exec-test': typeof ApiPublicExecTestRoute
  '/api/public/shopify': typeof ApiPublicShopifyRoute
  '/api/public/runner/pair': typeof ApiPublicRunnerPairRoute
  '/api/public/runner/poll': typeof ApiPublicRunnerPollRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_paired': typeof PairedRouteWithChildren
  '/pair': typeof PairRoute
  '/_paired/jbhifi': typeof PairedJbhifiRoute
  '/_paired/kmart': typeof PairedKmartRoute
  '/_paired/': typeof PairedIndexRoute
  '/api/public/exec-test': typeof ApiPublicExecTestRoute
  '/api/public/shopify': typeof ApiPublicShopifyRoute
  '/api/public/runner/pair': typeof ApiPublicRunnerPairRoute
  '/api/public/runner/poll': typeof ApiPublicRunnerPollRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/jbhifi'
    | '/kmart'
    | '/api/public/exec-test'
    | '/api/public/shopify'
    | '/api/public/runner/pair'
    | '/api/public/runner/poll'
    | '/api/public/runner/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/jbhifi'
    | '/kmart'
    | '/'
    | '/api/public/exec-test'
    | '/api/public/shopify'
    | '/api/public/runner/pair'
    | '/api/public/runner/poll'
    | '/api/public/runner/report'
  id:
    | '__root__'
    | '/_paired'
    | '/pair'
    | '/_paired/jbhifi'
    | '/_paired/kmart'
    | '/_paired/'
    | '/api/public/exec-test'
    | '/api/public/shopify'
    | '/api/public/runner/pair'
    | '/api/public/runner/poll'
    | '/api/public/runner/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PairedRoute: typeof PairedRouteWithChildren
  PairRoute: typeof PairRoute
  ApiPublicExecTestRoute: typeof ApiPublicExecTestRoute
  ApiPublicShopifyRoute: typeof ApiPublicShopifyRoute
  ApiPublicRunnerPairRoute: typeof ApiPublicRunnerPairRoute
  ApiPublicRunnerPollRoute: typeof ApiPublicRunnerPollRoute
  ApiPublicRunnerReportRoute: typeof ApiPublicRunnerReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_paired': {
      id: '/_paired'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PairedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_paired/': {
      id: '/_paired/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PairedIndexRouteImport
      parentRoute: typeof PairedRoute
    }
    '/_paired/kmart': {
      id: '/_paired/kmart'
      path: '/kmart'
      fullPath: '/kmart'
      preLoaderRoute: typeof PairedKmartRouteImport
      parentRoute: typeof PairedRoute
    }
    '/_paired/jbhifi': {
      id: '/_paired/jbhifi'
      path: '/jbhifi'
      fullPath: '/jbhifi'
      preLoaderRoute: typeof PairedJbhifiRouteImport
      parentRoute: typeof PairedRoute
    }
    '/api/public/shopify': {
      id: '/api/public/shopify'
      path: '/api/public/shopify'
      fullPath: '/api/public/shopify'
      preLoaderRoute: typeof ApiPublicShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exec-test': {
      id: '/api/public/exec-test'
      path: '/api/public/exec-test'
      fullPath: '/api/public/exec-test'
      preLoaderRoute: typeof ApiPublicExecTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/report': {
      id: '/api/public/runner/report'
      path: '/api/public/runner/report'
      fullPath: '/api/public/runner/report'
      preLoaderRoute: typeof ApiPublicRunnerReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/poll': {
      id: '/api/public/runner/poll'
      path: '/api/public/runner/poll'
      fullPath: '/api/public/runner/poll'
      preLoaderRoute: typeof ApiPublicRunnerPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/pair': {
      id: '/api/public/runner/pair'
      path: '/api/public/runner/pair'
      fullPath: '/api/public/runner/pair'
      preLoaderRoute: typeof ApiPublicRunnerPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PairedRouteChildren {
  PairedJbhifiRoute: typeof PairedJbhifiRoute
  PairedKmartRoute: typeof PairedKmartRoute
  PairedIndexRoute: typeof PairedIndexRoute
}

const PairedRouteChildren: PairedRouteChildren = {
  PairedJbhifiRoute: PairedJbhifiRoute,
  PairedKmartRoute: PairedKmartRoute,
  PairedIndexRoute: PairedIndexRoute,
}

const PairedRouteWithChildren =
  PairedRoute._addFileChildren(PairedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PairedRoute: PairedRouteWithChildren,
  PairRoute: PairRoute,
  ApiPublicExecTestRoute: ApiPublicExecTestRoute,
  ApiPublicShopifyRoute: ApiPublicShopifyRoute,
  ApiPublicRunnerPairRoute: ApiPublicRunnerPairRoute,
  ApiPublicRunnerPollRoute: ApiPublicRunnerPollRoute,
  ApiPublicRunnerReportRoute: ApiPublicRunnerReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
